"""add foreign key to reviews

Revision ID: 7ac93369b047
Revises: 028d4664b8ec
Create Date: 2024-04-15 15:40:11.735189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac93369b047'
down_revision = '028d4664b8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "employee_id",
            "reviews",
            ["employee_id"],
            ["id"],
        )
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
     with op.batch_alter_table('reviews', schema=None) as batch_op:
        op.drop_column("employee_id")